#!/usr/bin/env node
// video2mc — convert a video into a Minecraft post-effect that loops.
//
// Embeds every frame's pixels as packed RGB floats in a const float[] array
// inside the shader. The shader indexes into the array based on GameTime.
//
// Usage:
//   node video2mc.mjs <video> [options]
//
// Options:
//   --out <dir>         Resource-pack root (default: ".")
//   --name <name>       Effect name (default: sanitized video filename)
//   --namespace <ns>    Asset namespace (default: "minecraft")
//   --width <n>         Target width in pixels (default: 48)
//   --height <n>        Target height in pixels (default: auto, preserves aspect)
//   --fps <n>           Frame rate to extract (default: 10)
//   --duration <s>      Max duration to extract (default: full video)
//   --time-scale <n>    Seconds that GameTime's 0..1 maps to (default: 1200)
//   --loop <s>          Loop period in real seconds (default: video duration)
//   --blend <mode>      Blend mode: replace | overlay | multiply | add (default: replace)
//   --dry-run           Print stats without writing files
//
// Requires: ffmpeg on PATH

import { spawn } from "node:child_process";
import fs from "node:fs";
import path from "node:path";

// ---- Helpers ----
function sanitizeName(s) {
  return String(s).toLowerCase().replace(/[^a-z0-9_]+/g, "_").replace(/^_+|_+$/g, "") || "video";
}

function parseArgs(argv) {
  const args = { _: [] };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a.startsWith("--")) {
      const key = a.slice(2);
      if (key === "dry-run") args.dryRun = true;
      else args[key] = argv[++i];
    } else {
      args._.push(a);
    }
  }
  return args;
}

// ---- Get video info via ffprobe ----
function ffprobe(file) {
  return new Promise((resolve, reject) => {
    const proc = spawn("ffprobe", [
      "-v", "quiet",
      "-print_format", "json",
      "-show_streams",
      "-show_format",
      file,
    ], { stdio: ["pipe", "pipe", "pipe"] });
    let out = "";
    proc.stdout.on("data", (c) => (out += c));
    proc.on("error", reject);
    proc.on("close", (code) => {
      if (code !== 0) return reject(new Error("ffprobe exited " + code));
      try { resolve(JSON.parse(out)); } catch (e) { reject(e); }
    });
  });
}

// ---- Extract frames as raw RGB24 via ffmpeg ----
function extractFrames(file, opts) {
  return new Promise((resolve, reject) => {
    const args = [
      "-i", file,
      "-vf", "scale=" + opts.width + ":" + opts.height + ",fps=" + opts.fps,
      "-pix_fmt", "rgb24",
      "-f", "rawvideo",
    ];
    if (opts.duration) args.push("-t", String(opts.duration));
    args.push("pipe:1");

    const proc = spawn("ffmpeg", args, { stdio: ["pipe", "pipe", "pipe"] });
    const chunks = [];
    proc.stdout.on("data", (c) => chunks.push(c));
    let stderr = "";
    proc.stderr.on("data", (c) => (stderr += c));
    proc.on("error", reject);
    proc.on("close", (code) => {
      if (code !== 0) {
        reject(new Error("ffmpeg exited " + code + ": " + stderr.slice(-300)));
        return;
      }
      resolve(Buffer.concat(chunks));
    });
  });
}

// ---- Pack RGB bytes into a float (3 bytes -> 1 float) ----
function packRGB(r, g, b) {
  return r * 65536 + g * 256 + b;
}

// ---- Generate GLSL shader ----
function genShader(opts) {
  const { width, height, frameCount, fps, loopDuration, timeScale, blendMode } = opts;
  const totalPixels = width * height;
  const lines = [];

  lines.push("#version 330");
  lines.push("#extension GL_ARB_separate_shader_objects : require");
  lines.push("");
  lines.push("// Generated by video2mc — video embedded as packed RGB float array.");
  lines.push("// " + width + "x" + height + ", " + fps + " fps, " + frameCount + " frames, " + loopDuration.toFixed(2) + "s loop");
  lines.push("");
  lines.push("#include <minecraft:globals.glsl>");
  lines.push("");
  lines.push("uniform sampler2D iChan0Sampler;");
  lines.push("#define iChannel0 iChan0Sampler");
  lines.push("");
  lines.push("layout(location = 0) in vec2 texCoord;");
  lines.push("layout(location = 0) out vec4 fragColor;");
  lines.push("");

  // Emit the frame data
  const data = opts.frameData;
  const dataSize = totalPixels * frameCount;
  lines.push("const float FRAME_DATA[" + dataSize + "] = float[" + dataSize + "](");

  // Write values in rows of 16 for readability
  for (let i = 0; i < data.length; i += 16) {
    const row = data.slice(i, Math.min(i + 16, data.length));
    const comma = i + 16 < data.length ? "," : "";
    lines.push("    " + row.map(v => v.toFixed(0)).join(", ") + comma);
  }
  lines.push(");");
  lines.push("");

  // Constants
  lines.push("const int FW = " + width + ";");
  lines.push("const int FH = " + height + ";");
  lines.push("const float FRAME_COUNT = " + frameCount + ".0;");
  lines.push("const float VIDEO_FPS = " + fps + ".0;");
  lines.push("const float LOOP_DUR = " + loopDuration.toFixed(4) + ";");
  lines.push("");

  // Unpack helper
  lines.push("vec3 unpackRGB(float v) {");
  lines.push("    float r = floor(v / 65536.0) / 255.0;");
  lines.push("    float g = floor(mod(v, 65536.0) / 256.0) / 255.0;");
  lines.push("    float b = mod(v, 256.0) / 255.0;");
  lines.push("    return vec3(r, g, b);");
  lines.push("}");
  lines.push("");

  // Main
  lines.push("void main() {");
  lines.push("    float elapsed = GameTime * " + timeScale.toFixed(1) + ";");
  lines.push("    float videoTime = mod(elapsed, LOOP_DUR);");
  lines.push("    float frameF = floor(videoTime * VIDEO_FPS);");
  lines.push("    frameF = clamp(frameF, 0.0, FRAME_COUNT - 1.0);");
  lines.push("");
  lines.push("    vec2 uv = texCoord;");
  lines.push("    int px = int(uv.x * float(FW));");
  lines.push("    int py = int(uv.y * float(FH));");
  lines.push("    px = clamp(px, 0, FW - 1);");
  lines.push("    py = clamp(py, 0, FH - 1);");
  lines.push("    py = FH - 1 - py; // flip Y");
  lines.push("");
  lines.push("    int fidx = int(frameF);");
  lines.push("    int offset = fidx * FW * FH;");
  lines.push("    int idx = offset + py * FW + px;");
  lines.push("    vec3 videoColor = unpackRGB(FRAME_DATA[idx]);");
  lines.push("");

  // Blend with game
  if (blendMode === "replace") {
    lines.push("    fragColor = vec4(videoColor, 1.0);");
  } else if (blendMode === "overlay") {
    lines.push("    vec3 screen = texture(iChannel0, texCoord).rgb;");
    lines.push("    vec3 blended = screen * videoColor + screen * (1.0 - videoColor) * 2.0 * videoColor;");
    lines.push("    fragColor = vec4(clamp(blended, 0.0, 1.0), 1.0);");
  } else if (blendMode === "multiply") {
    lines.push("    vec3 screen = texture(iChannel0, texCoord).rgb;");
  lines.push("    fragColor = vec4(screen * videoColor, 1.0);");
  } else if (blendMode === "add") {
    lines.push("    vec3 screen = texture(iChannel0, texCoord).rgb;");
    lines.push("    fragColor = vec4(clamp(screen + videoColor, 0.0, 1.0), 1.0);");
  } else {
    lines.push("    fragColor = vec4(videoColor, 1.0);");
  }

  lines.push("}");
  lines.push("");
  return lines.join("\n");
}

// ---- Generate post_effect JSON ----
function genPostEffectJson(effectName, namespace) {
  const json = {
    passes: [{
      vertex_shader: "minecraft:core/screenquad",
      fragment_shader: namespace + ":post/" + effectName,
      inputs: [{ sampler_name: "iChan0", target: "minecraft:main" }],
      output: "minecraft:main",
    }],
  };
  return JSON.stringify(json, null, 4) + "\n";
}

// ---- Main ----
async function main() {
  const args = parseArgs(process.argv.slice(2));
  const videoFile = args._[0];
  if (!videoFile) {
    console.error("usage: node video2mc.mjs <video> [--out dir] [--name n] [--width 48] [--height auto] [--fps 10] [--duration s] [--loop s] [--blend replace|overlay|multiply|add] [--dry-run]");
    process.exit(1);
  }
  if (!fs.existsSync(videoFile)) {
    console.error("error: file not found: " + videoFile);
    process.exit(1);
  }

  const outRoot = args.out || ".";
  const namespace = sanitizeName(args.namespace || "minecraft");
  const targetWidth = Number(args.width || 48);
  const targetHeight = args.height === "auto" ? -1 : Number(args.height || -1);
  const fps = Number(args.fps || 10);
  const maxDuration = args.duration ? Number(args.duration) : null;
  const timeScale = Number(args["time-scale"] || 1200);
  const dryRun = !!args.dryRun;
  const blendMode = args.blend || "replace";

  // Get video info
  process.stderr.write("Probing " + videoFile + "... ");
  let info;
  try {
    info = await ffprobe(videoFile);
  } catch (e) {
    console.error("\nerror: ffprobe failed: " + e.message);
    process.exit(1);
  }
  const videoStream = info.streams.find(s => s.codec_type === "video");
  if (!videoStream) {
    console.error("\nerror: no video stream found");
    process.exit(1);
  }
  const srcWidth = videoStream.width;
  const srcHeight = videoStream.height;
  const srcDuration = Number(info.format.duration);
  const srcFps = eval(videoStream.r_frame_rate) || 30;

  // Compute target dimensions
  let width = targetWidth;
  let height = targetHeight;
  if (height <= 0) {
    height = Math.round((srcHeight / srcWidth) * width);
  }
  width = width & ~1;
  height = height & ~1;

  const duration = maxDuration ? Math.min(maxDuration, srcDuration) : srcDuration;
  const loopDuration = Number(args.loop) || duration;
  const frameCount = Math.ceil(duration * fps);

  process.stderr.write("ok\n");
  process.stderr.write("  Source:   " + srcWidth + "x" + srcHeight + " @ " + srcFps.toFixed(1) + "fps, " + srcDuration.toFixed(1) + "s\n");
  process.stderr.write("  Target:   " + width + "x" + height + " @ " + fps + "fps, " + duration.toFixed(1) + "s, " + frameCount + " frames\n");
  process.stderr.write("  Loop:     every " + loopDuration.toFixed(1) + "s\n");
  process.stderr.write("  Pixels:   " + (width * height * frameCount) + " (" + ((width * height * frameCount * 4) / 1024).toFixed(0) + " KB float data)\n");
  process.stderr.write("Extracting frames... ");

  // Extract frames
  let raw;
  try {
    raw = await extractFrames(videoFile, { width, height, fps, duration: maxDuration });
  } catch (e) {
    console.error("\nerror: ffmpeg failed: " + e.message);
    process.exit(1);
  }

  const expectedBytes = width * height * 3 * frameCount;
  const actualFrames = Math.floor(raw.length / (width * height * 3));

  process.stderr.write("ok (" + actualFrames + " frames)\n");

  // Pack pixels
  process.stderr.write("Packing pixels... ");
  const pixelCount = width * height * actualFrames;
  const frameData = new Float64Array(pixelCount);
  for (let i = 0; i < pixelCount; i++) {
    const off = i * 3;
    frameData[i] = packRGB(raw[off], raw[off + 1], raw[off + 2]);
  }
  process.stderr.write("ok\n");

  // Generate
  const effectName = sanitizeName(args.name || path.basename(videoFile, path.extname(videoFile)));

  const shaderSource = genShader({
    width, height, frameCount: actualFrames, fps,
    loopDuration, timeScale, blendMode,
    frameData: Array.from(frameData),
  });

  const postJson = genPostEffectJson(effectName, namespace);

  const fshPath = "assets/" + namespace + "/shaders/post/" + effectName + ".fsh";
  const jsonPath = "assets/" + namespace + "/post_effect/" + effectName + ".json";
  const outputs = [
    { path: fshPath, content: shaderSource, size: shaderSource.length },
    { path: jsonPath, content: postJson, size: postJson.length },
  ];

  // Write
  if (dryRun) {
    console.log("\n[Dry run] Would write " + outputs.length + " files to " + path.resolve(outRoot) + ":");
    for (const o of outputs) {
      console.log("  " + o.path + "  (" + (o.size / 1024).toFixed(0) + " KB)");
    }
  } else {
    for (const o of outputs) {
      const full = path.join(outRoot, o.path);
      fs.mkdirSync(path.dirname(full), { recursive: true });
      fs.writeFileSync(full, o.content);
    }
  }

  // Report
  console.log("\nvideo2mc: \"" + effectName + "\"");
  console.log("  source:  " + videoFile);
  console.log("  target:  " + width + "x" + height + ", " + fps + " fps, " + actualFrames + " frames, " + loopDuration.toFixed(1) + "s loop");
  console.log("  blend:   " + blendMode);
  console.log("  files:");
  for (const o of outputs) {
    console.log("    " + (dryRun ? "(dry) " : "") + path.join(outRoot, o.path) + "  (" + (o.size / 1024).toFixed(0) + " KB)");
  }
  console.log("");
  console.log("  Enable: /post-effect " + effectName);
}

main();
