#!/usr/bin/env node
// video2mc — convert a video into a Minecraft 26.3+ post-effect that loops.
//
// Embeds frame pixels as packed RGB floats in const arrays inside GLSL.
// When the video exceeds --max-pixels (default 100000), it splits across
// multiple shader passes chained via minecraft:swap0/swap1 buffers.
// Each pass only activates for its frame range and passes through otherwise.
//
// Usage:
//   node video2mc.mjs <video> [options]
//
// Options:
//   --out <dir>         Resource-pack root (default: ".")
//   --name <name>       Effect name (default: sanitized video filename)
//   --namespace <ns>    Asset namespace (default: "minecraft")
//   --width <n>         Target width in pixels (default: 48)
//   --height <n>        Target height in pixels (default: auto, preserves aspect)
//   --fps <n>           Frame rate to extract (default: 10)
//   --duration <s>      Max duration to extract (default: full video)
//   --time-scale <n>    Multiplier for GameTime (default: 1.0)
//   --loop <s>          Loop period in GameTime-scaled seconds (default: video duration)
//   --blend <mode>      Blend mode: replace | overlay | multiply | add (default: replace)
//   --max-pixels <n>    Max pixels per shader pass (default: 100000)
//   --dry-run           Print stats without writing files
//
// Requires: ffmpeg on PATH (system package, e.g. `apt install ffmpeg`)

import { spawn } from "node:child_process";
import fs from "node:fs";
import path from "node:path";

// ---- Helpers ----
function sanitizeName(s) {
  return String(s)
    .toLowerCase()
    .replace(/[^a-z0-9_]+/g, "_")
    .replace(/^_+|_+$/g, "") || "video";
}

function parseArgs(argv) {
  const args = { _: [] };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a.startsWith("--")) {
      const key = a.slice(2);
      if (key === "dry-run") args.dryRun = true;
      else args[key] = argv[++i];
    } else {
      args._.push(a);
    }
  }
  return args;
}

// ---- Get video info via ffprobe ----
function ffprobe(file) {
  return new Promise((resolve, reject) => {
    const proc = spawn(
      "ffprobe",
      ["-v", "quiet", "-print_format", "json", "-show_streams", "-show_format", file],
      { stdio: ["pipe", "pipe", "pipe"] },
    );
    let out = "";
    proc.stdout.on("data", (c) => (out += c));
    proc.on("error", reject);
    proc.on("close", (code) => {
      if (code !== 0) return reject(new Error("ffprobe exited " + code));
      try { resolve(JSON.parse(out)); } catch (e) { reject(e); }
    });
  });
}

// ---- Extract frames as raw RGB24 via ffmpeg ----
function extractFrames(file, opts) {
  return new Promise((resolve, reject) => {
    const args = [
      "-i", file,
      "-vf", "scale=" + opts.width + ":" + opts.height + ",fps=" + opts.fps,
      "-pix_fmt", "rgb24",
      "-f", "rawvideo",
    ];
    if (opts.duration) args.push("-t", String(opts.duration));
    args.push("pipe:1");
    const proc = spawn("ffmpeg", args, { stdio: ["pipe", "pipe", "pipe"] });
    const chunks = [];
    proc.stdout.on("data", (c) => chunks.push(c));
    let stderr = "";
    proc.stderr.on("data", (c) => (stderr += c));
    proc.on("error", reject);
    proc.on("close", (code) => {
      if (code !== 0) {
        reject(new Error("ffmpeg exited " + code + ": " + stderr.slice(-300)));
        return;
      }
      resolve(Buffer.concat(chunks));
    });
  });
}

// ---- Pack RGB bytes into a float (3 bytes -> 1 float) ----
function packRGB(r, g, b) {
  return r * 65536 + g * 256 + b;
}

// ---- Auto-scale resolution to fit at least 1 frame per chunk ----
function autoScale(srcWidth, srcHeight, srcDuration, fps, maxPixels) {
  let width = srcWidth;
  let height = srcHeight;
  const aspect = srcHeight / srcWidth;
  const minDim = 4;
  const warnings = [];

  const pixelsPerFrame = width * height;
  if (pixelsPerFrame <= maxPixels) return { width, height, warnings };

  for (let w = srcWidth; w >= minDim; w -= 2) {
    const h = Math.max(minDim, Math.round(aspect * w) & ~1);
    if (w * h <= maxPixels) { width = w; height = h; break; }
  }
  warnings.push("Resolution reduced to " + width + "x" + height + " to fit SPIR-V constant limit (" + maxPixels + " pixels per pass)");
  return { width, height, warnings };
}

// ---- Generate a single-chunk shader ----
function genSingleShader(opts) {
  const { width, height, frameCount, fps, loopDuration, timeScale, blendMode, frameData } = opts;
  const totalPixels = width * height * frameCount;
  const lines = [];

  lines.push("#version 330");
  lines.push("#extension GL_ARB_separate_shader_objects : require");
  lines.push("");
  lines.push("// Generated by video2mc — single pass, " + frameCount + " frames.");
  lines.push("");
  lines.push("#include <minecraft:globals.glsl>");
  lines.push("");
  if (blendMode !== "replace") {
    lines.push("uniform sampler2D iChan0Sampler;");
    lines.push("#define iChannel0 iChan0Sampler");
    lines.push("");
  }
  lines.push("layout(location = 0) in vec2 texCoord;");
  lines.push("layout(location = 0) out vec4 fragColor;");
  lines.push("");
  lines.push("const float FRAME_DATA[" + totalPixels + "] = float[" + totalPixels + "](");
  for (let i = 0; i < frameData.length; i += 16) {
    const row = frameData.slice(i, Math.min(i + 16, frameData.length));
    const comma = i + 16 < frameData.length ? "," : "";
    lines.push("    " + row.join(", ") + comma);
  }
  lines.push(");");
  lines.push("");
  lines.push("const int FW = " + width + ";");
  lines.push("const int FH = " + height + ";");
  lines.push("const float FRAME_COUNT = " + frameCount + ".0;");
  lines.push("const float VIDEO_FPS = " + fps + ".0;");
  lines.push("const float LOOP_DUR = " + loopDuration.toFixed(4) + ";");
  lines.push("");
  lines.push("vec3 unpackRGB(float v) {");
  lines.push("    float r = floor(v / 65536.0) / 255.0;");
  lines.push("    float g = floor(mod(v, 65536.0) / 256.0) / 255.0;");
  lines.push("    float b = mod(v, 256.0) / 255.0;");
  lines.push("    return vec3(r, g, b);");
  lines.push("}");
  lines.push("");
  lines.push("void main() {");
  lines.push("    float elapsed = GameTime * " + timeScale.toFixed(4) + ";");
  lines.push("    float videoTime = mod(elapsed, LOOP_DUR);");
  lines.push("    float frameF = floor(videoTime * VIDEO_FPS);");
  lines.push("    frameF = clamp(frameF, 0.0, FRAME_COUNT - 1.0);");
  lines.push("");
  lines.push("    int px = int(texCoord.x * float(FW));");
  lines.push("    int py = int(texCoord.y * float(FH));");
  lines.push("    px = clamp(px, 0, FW - 1);");
  lines.push("    py = clamp(py, 0, FH - 1);");
  lines.push("    py = FH - 1 - py;");
  lines.push("");
  lines.push("    int fidx = int(frameF);");
  lines.push("    int idx = fidx * FW * FH + py * FW + px;");
  lines.push("    vec3 videoColor = unpackRGB(FRAME_DATA[idx]);");
  lines.push("");
  appendBlend(lines, blendMode, false);
  lines.push("}");
  lines.push("");
  return lines.join("\n");
}

// ---- Generate a multi-pass chunk shader ----
function genChunkShader(opts) {
  const { width, height, totalFrames, fps, loopDuration, timeScale, blendMode,
          passIndex, framesPerChunk, chunkFrameCount, frameData } = opts;
  const pixelsInChunk = width * height * chunkFrameCount;
  const lines = [];

  lines.push("#version 330");
  lines.push("#extension GL_ARB_separate_shader_objects : require");
  lines.push("");
  lines.push("// Generated by video2mc — chunk " + passIndex + ", frames " +
    (passIndex * framesPerChunk) + "-" + (passIndex * framesPerChunk + chunkFrameCount - 1) +
    " of " + totalFrames + ".");
  lines.push("");
  lines.push("#include <minecraft:globals.glsl>");
  lines.push("");
  lines.push("uniform sampler2D iChan0Sampler;");
  lines.push("#define iChannel0 iChan0Sampler");
  lines.push("");
  lines.push("layout(location = 0) in vec2 texCoord;");
  lines.push("layout(location = 0) out vec4 fragColor;");
  lines.push("");
  lines.push("const float FRAME_DATA[" + pixelsInChunk + "] = float[" + pixelsInChunk + "](");
  for (let i = 0; i < frameData.length; i += 16) {
    const row = frameData.slice(i, Math.min(i + 16, frameData.length));
    const comma = i + 16 < frameData.length ? "," : "";
    lines.push("    " + row.join(", ") + comma);
  }
  lines.push(");");
  lines.push("");
  lines.push("const int FW = " + width + ";");
  lines.push("const int FH = " + height + ";");
  lines.push("const int PASS_INDEX = " + passIndex + ";");
  lines.push("const int FRAMES_PER_CHUNK = " + framesPerChunk + ";");
  lines.push("const float TOTAL_FRAMES = " + totalFrames + ".0;");
  lines.push("const float VIDEO_FPS = " + fps + ".0;");
  lines.push("const float LOOP_DUR = " + loopDuration.toFixed(4) + ";");
  lines.push("");
  lines.push("vec3 unpackRGB(float v) {");
  lines.push("    float r = floor(v / 65536.0) / 255.0;");
  lines.push("    float g = floor(mod(v, 65536.0) / 256.0) / 255.0;");
  lines.push("    float b = mod(v, 256.0) / 255.0;");
  lines.push("    return vec3(r, g, b);");
  lines.push("}");
  lines.push("");
  lines.push("void main() {");
  lines.push("    float elapsed = GameTime * " + timeScale.toFixed(4) + ";");
  lines.push("    float videoTime = mod(elapsed, LOOP_DUR);");
  lines.push("    float frameF = floor(videoTime * VIDEO_FPS);");
  lines.push("    frameF = clamp(frameF, 0.0, TOTAL_FRAMES - 1.0);");
  lines.push("");
  lines.push("    int globalFrame = int(frameF);");
  lines.push("    int chunkIdx = globalFrame / FRAMES_PER_CHUNK;");
  lines.push("");
  lines.push("    if (chunkIdx == PASS_INDEX) {");
  lines.push("        int localFrame = globalFrame - PASS_INDEX * FRAMES_PER_CHUNK;");
  lines.push("        int px = int(texCoord.x * float(FW));");
  lines.push("        int py = int(texCoord.y * float(FH));");
  lines.push("        px = clamp(px, 0, FW - 1);");
  lines.push("        py = clamp(py, 0, FH - 1);");
  lines.push("        py = FH - 1 - py;");
  lines.push("        int idx = localFrame * FW * FH + py * FW + px;");
  lines.push("        vec3 videoColor = unpackRGB(FRAME_DATA[idx]);");
  lines.push("");
  appendBlend(lines, blendMode, true);
  lines.push("    } else {");
  lines.push("        fragColor = vec4(texture(iChannel0, texCoord).rgb, 1.0);");
  lines.push("    }");
  lines.push("}");
  lines.push("");
  return lines.join("\n");
}

// ---- Append blend logic ----
function appendBlend(lines, blendMode, indented) {
  const p = indented ? "        " : "    ";
  if (blendMode === "replace") {
    lines.push(p + "fragColor = vec4(videoColor, 1.0);");
  } else if (blendMode === "overlay") {
    lines.push(p + "vec3 sc = texture(iChannel0, texCoord).rgb;");
    lines.push(p + "vec3 ov = vec3(");
    lines.push(p + "    sc.r < 0.5 ? 2.0 * sc.r * videoColor.r : 1.0 - 2.0 * (1.0 - sc.r) * (1.0 - videoColor.r),");
    lines.push(p + "    sc.g < 0.5 ? 2.0 * sc.g * videoColor.g : 1.0 - 2.0 * (1.0 - sc.g) * (1.0 - videoColor.g),");
    lines.push(p + "    sc.b < 0.5 ? 2.0 * sc.b * videoColor.b : 1.0 - 2.0 * (1.0 - sc.b) * (1.0 - videoColor.b)");
    lines.push(p + ");");
    lines.push(p + "fragColor = vec4(clamp(ov, 0.0, 1.0), 1.0);");
  } else if (blendMode === "multiply") {
    lines.push(p + "vec3 sc = texture(iChannel0, texCoord).rgb;");
    lines.push(p + "fragColor = vec4(sc * videoColor, 1.0);");
  } else if (blendMode === "add") {
    lines.push(p + "vec3 sc = texture(iChannel0, texCoord).rgb;");
    lines.push(p + "fragColor = vec4(clamp(sc + videoColor, 0.0, 1.0), 1.0);");
  } else {
    lines.push(p + "fragColor = vec4(videoColor, 1.0);");
  }
}

// ---- Generate post_effect JSON (single pass) ----
function genSinglePassJson(effectName, namespace, blendMode) {
  const inputs = [];
  if (blendMode !== "replace") {
    inputs.push({ sampler_name: "iChan0", target: "minecraft:main" });
  }
  return JSON.stringify({
    passes: [{
      vertex_shader: "minecraft:core/screenquad",
      fragment_shader: namespace + ":post/" + effectName,
      inputs: inputs,
      output: "minecraft:main",
    }],
  }, null, 4) + "\n";
}

// ---- Generate post_effect JSON (multi-pass chained via swap buffers) ----
function genMultiPassJson(effectName, namespace, numChunks, blendMode) {
  const passes = [];
  for (let c = 0; c < numChunks; c++) {
    const isLast = c === numChunks - 1;
    let input, output;
    if (c === 0) {
      input = "minecraft:main";
    } else {
      // Previous pass's output
      input = (c - 1) % 2 === 0 ? "minecraft:swap0" : "minecraft:swap1";
    }
    if (isLast) {
      output = "minecraft:main";
    } else {
      output = c % 2 === 0 ? "minecraft:swap0" : "minecraft:swap1";
    }
    passes.push({
      vertex_shader: "minecraft:core/screenquad",
      fragment_shader: namespace + ":post/" + effectName + "_" + c,
      inputs: [{ sampler_name: "iChan0", target: input }],
      output: output,
    });
  }
  return JSON.stringify({ passes: passes }, null, 4) + "\n";
}

// ---- Main ----
async function main() {
  const args = parseArgs(process.argv.slice(2));
  const videoFile = args._[0];
  if (!videoFile) {
    process.stderr.write(
      "usage: node video2mc.mjs <video> [--out dir] [--name n] [--width 48] [--height auto] " +
      "[--fps 10] [--duration s] [--time-scale 1.0] [--loop s] " +
      "[--blend replace|overlay|multiply|add] [--max-pixels 100000] [--dry-run]\n",
    );
    process.exit(1);
  }
  if (!fs.existsSync(videoFile)) {
    process.stderr.write("error: file not found: " + videoFile + "\n");
    process.exit(1);
  }

  const outRoot = args.out || ".";
  const namespace = sanitizeName(args.namespace || "minecraft");
  const targetWidth = Number(args.width || 48);
  const targetHeight = args.height === "auto" ? -1 : Number(args.height || -1);
  const fps = Number(args.fps || 10);
  const maxDuration = args.duration ? Number(args.duration) : null;
  const timeScale = Number(args["time-scale"] || 1.0);
  const dryRun = !!args["dry-run"];
  const blendMode = args.blend || "replace";
  const maxPixels = Number(args["max-pixels"] || 100000);

  // Get video info
  process.stderr.write("Probing " + videoFile + "... ");
  let info;
  try {
    info = await ffprobe(videoFile);
  } catch (e) {
    process.stderr.write("\nerror: ffprobe failed: " + e.message + "\n");
    process.exit(1);
  }
  const videoStream = info.streams.find((s) => s.codec_type === "video");
  if (!videoStream) {
    process.stderr.write("\nerror: no video stream found\n");
    process.exit(1);
  }
  const srcWidth = videoStream.width;
  const srcHeight = videoStream.height;
  const srcDuration = Number(info.format.duration);
  const srcFps = eval(videoStream.r_frame_rate) || 30;

  // Compute target dimensions
  let width = targetWidth;
  let height = targetHeight;
  if (height <= 0) {
    height = Math.round((srcHeight / srcWidth) * width);
  }
  width = width & ~1;
  height = height & ~1;

  const duration = maxDuration ? Math.min(maxDuration, srcDuration) : srcDuration;
  const loopDuration = Number(args.loop) || duration;
  const frameCount = Math.ceil(duration * fps);

  // Auto-scale resolution if a single frame exceeds maxPixels
  const scaled = autoScale(width, height, duration, fps, maxPixels);
  if (scaled.warnings.length) {
    for (const w of scaled.warnings) process.stderr.write("WARNING: " + w + "\n");
  }
  width = scaled.width;
  height = scaled.height;

  const pixelsPerFrame = width * height;
  const totalPixels = pixelsPerFrame * frameCount;
  const framesPerChunk = Math.floor(maxPixels / pixelsPerFrame);
  const numChunks = Math.ceil(frameCount / framesPerChunk);
  const isMultiPass = numChunks > 1;

  process.stderr.write("ok\n");
  process.stderr.write("  Source:    " + srcWidth + "x" + srcHeight + " @ " + srcFps.toFixed(1) + "fps, " + srcDuration.toFixed(1) + "s\n");
  process.stderr.write("  Target:    " + width + "x" + height + " @ " + fps + " fps, " + duration.toFixed(1) + "s, " + frameCount + " frames\n");
  process.stderr.write("  Pixels:    " + totalPixels + " total, " + framesPerChunk + " frames/chunk, " + numChunks + " passes\n");
  process.stderr.write("  Loop:      every " + loopDuration.toFixed(1) + "s (GameTime-scaled)\n");
  process.stderr.write("  Blend:     " + blendMode + "\n");
  process.stderr.write("Extracting frames... ");

  // Extract frames
  let raw;
  try {
    raw = await extractFrames(videoFile, { width, height, fps, duration: maxDuration });
  } catch (e) {
    process.stderr.write("\nerror: ffmpeg failed: " + e.message + "\n");
    process.exit(1);
  }
  const actualFrames = Math.floor(raw.length / (width * height * 3));
  process.stderr.write("ok (" + actualFrames + " frames)\n");

  const effectName = sanitizeName(args.name || path.basename(videoFile, path.extname(videoFile)));
  const outputs = [];
  const bytesPerFrame = pixelsPerFrame * 3;

  if (!isMultiPass) {
    // ---- Single pass: all frames in one shader ----
    process.stderr.write("Packing pixels... ");
    const pixelCount = pixelsPerFrame * actualFrames;
    const frameData = new Array(pixelCount);
    for (let i = 0; i < pixelCount; i++) {
      const off = i * 3;
      frameData[i] = packRGB(raw[off], raw[off + 1], raw[off + 2]);
    }
    process.stderr.write("ok\n");

    const shader = genSingleShader({
      width, height, frameCount: actualFrames, fps,
      loopDuration, timeScale, blendMode, frameData,
    });
    const json = genSinglePassJson(effectName, namespace, blendMode);
    outputs.push({ path: "assets/" + namespace + "/shaders/post/" + effectName + ".fsh", content: shader, size: shader.length });
    outputs.push({ path: "assets/" + namespace + "/post_effect/" + effectName + ".json", content: json, size: json.length });
  } else {
    // ---- Multi-pass: split frames across chunks ----
    for (let c = 0; c < numChunks; c++) {
      const startFrame = c * framesPerChunk;
      const endFrame = Math.min(startFrame + framesPerChunk, actualFrames);
      const chunkFrames = endFrame - startFrame;
      const chunkPixels = pixelsPerFrame * chunkFrames;

      process.stderr.write("Packing chunk " + (c + 1) + "/" + numChunks + " (" + chunkFrames + " frames)... ");
      const frameData = new Array(chunkPixels);
      for (let f = 0; f < chunkFrames; f++) {
        const frameByteOff = (startFrame + f) * bytesPerFrame;
        const chunkPixelOff = f * pixelsPerFrame;
        for (let p = 0; p < pixelsPerFrame; p++) {
          const si = frameByteOff + p * 3;
          frameData[chunkPixelOff + p] = packRGB(raw[si], raw[si + 1], raw[si + 2]);
        }
      }
      process.stderr.write("ok\n");

      const shader = genChunkShader({
        width, height, totalFrames: actualFrames, fps,
        loopDuration, timeScale, blendMode,
        passIndex: c, framesPerChunk, chunkFrameCount: chunkFrames, frameData,
      });
      outputs.push({
        path: "assets/" + namespace + "/shaders/post/" + effectName + "_" + c + ".fsh",
        content: shader, size: shader.length,
      });
    }

    const json = genMultiPassJson(effectName, namespace, numChunks, blendMode);
    outputs.push({ path: "assets/" + namespace + "/post_effect/" + effectName + ".json", content: json, size: json.length });
  }

  // Write
  if (dryRun) {
    console.log("\n[Dry run] Would write " + outputs.length + " files to " + path.resolve(outRoot) + ":");
    for (const o of outputs) {
      console.log("  " + o.path + "  (" + (o.size / 1024).toFixed(0) + " KB)");
    }
  } else {
    for (const o of outputs) {
      const full = path.join(outRoot, o.path);
      fs.mkdirSync(path.dirname(full), { recursive: true });
      fs.writeFileSync(full, o.content, "utf8");
    }
  }

  // Report
  console.log("\nvideo2mc: \"" + effectName + "\"");
  console.log("  source:   " + videoFile);
  console.log("  target:   " + width + "x" + height + ", " + fps + " fps, " + actualFrames + " frames, " + loopDuration.toFixed(1) + "s loop");
  console.log("  passes:   " + numChunks + " (" + framesPerChunk + " frames/chunk, " + maxPixels + " max pixels/chunk)");
  console.log("  blend:    " + blendMode);
  console.log("  files:");
  for (const o of outputs) {
    console.log("    " + (dryRun ? "(dry) " : "") + path.join(outRoot, o.path) + "  (" + (o.size / 1024).toFixed(0) + " KB)");
  }
  console.log("");
  console.log("  Enable: /post-effect " + effectName);
}

main();
